const LATITUDE_DELTA = 0.0922
const LONGITUDE_DELTA = 0.0421

export default {
  ANDROID: 'android',
  GOOGLE_API_KEY: 'AIzaSyArTD2oId5AfnDoHd9CR0KQbH4utjGZcE8',
  LOCATIONS_LIMIT_MAX: 5,
  LOCATIONS_LIMIT_MIN: 2,
  LATITUDE_DELTA: LATITUDE_DELTA,
  LONGITUDE_DELTA: LONGITUDE_DELTA,
  AUCKLAND_MAP_REGION: {
    latitude: -36.848461,
    longitude: 174.763336,
    latitudeDelta: LATITUDE_DELTA,
    longitudeDelta: LONGITUDE_DELTA
  }
}
